//
// Created by noreasonexception on 4/10/18.
//

#ifndef IKARUS_PROJECT_STATES_H
#define IKARUS_PROJECT_STATES_H
#define SINGLE_OPTION_DIALOG_STATE_PATH                 "/SINGLEOPTION"
    #define TWO_BUTTONS_DIALOG_STATE_PATH               "/TWOBUTTONS"
        #define SET_LATENCY_DIALOG_STATE_PATH           "/SETLATENCY"
            #define LATENCY_INPUT_QLINEEDIT_STATE       "/LATENCYQLINEEDIT"
        #define SET_RESOLUTION_DIALOG_STATE_PATH        "/SETRESOLUTION"
            #define RESOLUTION_WIDTH_QLINEEDIT_STATE    "/RESOLUTIONWIDTH"
            #define RESOLUTION_HEIGHT_QLINEEDIT_STATE   "/RESOLUTIONHEIGHT"
    #define MULTIPLE_CHOICE_DIALOG_STATE_PATH           "/MULTIPLECHOICE"
        #define SET_DRONE_ADDR_DIALOG_STATE_PATH        "/SETDRONEADDR"
        #define SET_SERVERS_ADDR_DIALOG_STATE_PATH      "/SETSERVERSADDR"

#endif //IKARUS_PROJECT_STATES_H
