//
// Created by noreasonexception on 5/4/18.
//

#ifndef IKARUS_PROJECT_SETRESOLUTIONDIALOGTEXT_H
#define IKARUS_PROJECT_SETRESOLUTIONDIALOGTEXT_H
#define SET_RESOLUTION_DIALOG_WIDTH_QLABEL "Width:"
#define SET_RESOLUTION_DIALOG_HEIGHT_QLABEL "Height:"
#endif //IKARUS_PROJECT_SETRESOLUTIONDIALOG_H
