//
// Created by noreasonexception on 5/4/18.
//

#ifndef IKARUS_PROJECT_SETDRONEADDRDIALOGTEXT_H
#define IKARUS_PROJECT_SETDRONEADDRDIALOGTEXT_H
#define SET_DRONE_ADDR_DIALOG_ADD_BTN "+"
#endif //IKARUS_PROJECT_SETDRONEADDRDIALOGTEXT_H
