//
// Created by noreasonexception on 5/4/18.
//

#ifndef IKARUS_PROJECT_DATAPANELTEXT_H
#define IKARUS_PROJECT_DATAPANELTEXT_H
#define DATA_PANEL_TITLE "Data"
#endif //IKARUS_PROJECT_DATAPANELTEXT_H
