//
// Created by noreasonexception on 5/3/18.
//

#ifndef IKARUS_PROJECT_INFORMATIONOBJECTSUPPLIER_H
#define IKARUS_PROJECT_INFORMATIONOBJECTSUPPLIER_H
#define MAINWINDOW_DATAEXPORTER_SUPPLIER    "MainWindowDataExporterSupplier"
#define MAINWINDOW_LOGEXPORTER_SUPPLIER     "MainWindowLogExporterSupplier"
#endif //IKARUS_PROJECT_INFORMATIONOBJECTSUPPLIER_H
