//
// Created by noreasonexception on 5/4/18.
//

#ifndef IKARUS_PROJECT_SETSERVERSADDRDIALOGTEXT_H
#define IKARUS_PROJECT_SETSERVERSADDRDIALOGTEXT_H
#define SET_SERVER_ADDR_DIALOG_ADD_BTN "+"
#endif //IKARUS_PROJECT_SETSERVERSADDRDIALOGTEXT_H
