//
// Created by noreasonexception on 5/4/18.
//

#ifndef IKARUS_PROJECT_ALANSINGLEOPTIONDIALOGTEXT_H
#define IKARUS_PROJECT_ALANSINGLEOPTIONDIALOGTEXT_H

#endif //IKARUS_PROJECT_ALANSINGLEOPTIONDIALOGTEXT_H
