//
// Created by noreasonexception on 4/14/18.
//

#ifndef IKARUS_PROJECT_QSETTINGS_H
#define IKARUS_PROJECT_QSETTINGS_H
/****
 * This constraints is used with QSettings object as keys in key-value pairs of configuration settings
 * in RTSP Subsystem
 */
#define ALAN_DEFAULT_RTSP_QSETTING_LATENCY              "LATENCYOPTION"
#define ALAN_DEFAULT_RTSP_QSETTING_RESOLUTION_WIDTH     "RESOLUTION/WIDTHOPTION"
#define ALAN_DEFAULT_RTSP_QSETTING_RESOLUTION_HEIGHT    "RESOLUTION/HEIGHTOPTION"
#define ALAN_DEFAULT_RTSP_QSETTING_SERVER_LOCATION      "SERVERLOCATIONOPTION"
#define ALAN_DEFAULT_RTSP_QSETTING_VIDEO_FILE_LOCATION  "VIDEOFILELOCATIONOPTION"
#endif //IKARUS_PROJECT_QSETTINGS_H
