//
// Created by noreasonexception on 4/14/18.
//

#ifndef IKARUS_PROJECT_QSETTINGS_H
#define IKARUS_PROJECT_QSETTINGS_H

#define ALAN_DEFAULT_RTSP_QSETTING_LATENCY           "LATENCYOPTION"
#define ALAN_DEFAULT_RTSP_QSETTING_RESOLUTION_WIDTH  "RESOLUTION/WIDTHOPTION"
#define ALAN_DEFAULT_RTSP_QSETTING_RESOLUTION_HEIGHT "RESOLUTION/HEIGHTOPTION"
#endif //IKARUS_PROJECT_QSETTINGS_H
