//
// Created by noreasonexception on 5/4/18.
//

#ifndef IKARUS_PROJECT_SETLATENCYDIALOGTEXT_H
#define IKARUS_PROJECT_SETLATENCYDIALOGTEXT_H
#define SET_LATENCY_DIALOG_MEASUREMENT_UNIT_QLABEL "ms"
#endif //IKARUS_PROJECT_SETLATENCYDIALOGTEXT_H
