//
// Created by noreasonexception on 5/4/18.
//

#ifndef IKARUS_PROJECT_ALANTWOBUTTONDIALOGTEXT_H
#define IKARUS_PROJECT_ALANTWOBUTTONDIALOGTEXT_H
#define ALAN_TWO_BUTTON_DIALOG_BTN1 "Cancel"
#define ALAN_TWO_BUTTON_DIALOG_BTN2 "OK"
#endif //IKARUS_PROJECT_ALANTWOBUTTONDIALOG_H
